language: go
go: ["1.13"]
script:
- go get
- go test .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- TARGET="j18e/flog:${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}"
- docker build -t ${TARGET} .
- docker push ${TARGET}
